"""add fields in movie

Revision ID: 167f03a7053c
Revises: 36c91f9a0253
Create Date: 2025-06-19 14:38:14.287783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167f03a7053c'
down_revision: Union[str, None] = '36c91f9a0253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('director', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('cast', sa.String(length=1000), nullable=True))
    op.add_column('movies', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('movies', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('genre', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'year')
    op.drop_column('movies', 'country')
    op.drop_column('movies', 'cast')
    op.drop_column('movies', 'director')
    # ### end Alembic commands ###
