"""add duration to audio_track

Revision ID: 3753faa57581
Revises: 81b33dbebe97
Create Date: 2025-06-25 20:23:05.523711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3753faa57581'
down_revision: Union[str, None] = '81b33dbebe97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_tracks', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_tracks', 'duration')
    # ### end Alembic commands ###
