"""Add ON DELETE CASCADE to audio_fingerprints.movie_id

Revision ID: 418d7b0432c3
Revises: 6adeb6a59262
Create Date: 2025-06-02 15:39:48.768368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418d7b0432c3'
down_revision: Union[str, None] = '6adeb6a59262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audio_fingerprints_ibfk_1'), 'audio_fingerprints', type_='foreignkey')
    op.create_foreign_key(None, 'audio_fingerprints', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_fingerprints', type_='foreignkey')
    op.create_foreign_key(op.f('audio_fingerprints_ibfk_1'), 'audio_fingerprints', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
