"""switch to hash-pair fingerprints

Revision ID: 81b33dbebe97
Revises: 7a7304f05c3e
Create Date: 2025-06-23 04:59:56.459607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81b33dbebe97'
down_revision: Union[str, None] = '7a7304f05c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_fingerprints', sa.Column('hash', sa.String(length=16), nullable=False))
    op.add_column('audio_fingerprints', sa.Column('offset', sa.Float(), nullable=False))
    op.drop_column('audio_fingerprints', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_fingerprints', sa.Column('timestamp', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('audio_fingerprints', 'offset')
    op.drop_column('audio_fingerprints', 'hash')
    # ### end Alembic commands ###
