"""refactor models: tracks, subscription, poster

Revision ID: 8651b31304ef
Revises: 418d7b0432c3
Create Date: 2025-06-09 16:35:03.195112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8651b31304ef'
down_revision: Union[str, None] = '418d7b0432c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('track_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_tracks_id'), 'audio_tracks', ['id'], unique=False)
    op.add_column('audio_fingerprints', sa.Column('audio_track_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('audio_fingerprints_ibfk_1'), 'audio_fingerprints', type_='foreignkey')
    op.create_foreign_key(None, 'audio_fingerprints', 'audio_tracks', ['audio_track_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audio_fingerprints', 'movie_id')
    op.add_column('movies', sa.Column('poster_url', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('description', sa.String(length=1000), nullable=True))
    op.drop_index(op.f('fingerprint_hash'), table_name='movies')
    op.drop_column('movies', 'fingerprint_hash')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('has_subscription', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'has_subscription')
    op.drop_column('users', 'is_admin')
    op.add_column('movies', sa.Column('fingerprint_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.create_index(op.f('fingerprint_hash'), 'movies', ['fingerprint_hash'], unique=True)
    op.drop_column('movies', 'description')
    op.drop_column('movies', 'poster_url')
    op.add_column('audio_fingerprints', sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audio_fingerprints', type_='foreignkey')
    op.create_foreign_key(op.f('audio_fingerprints_ibfk_1'), 'audio_fingerprints', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audio_fingerprints', 'audio_track_id')
    op.drop_index(op.f('ix_audio_tracks_id'), table_name='audio_tracks')
    op.drop_table('audio_tracks')
    # ### end Alembic commands ###
