"""add verification code fields

Revision ID: 919f4bfab574
Revises: 8651b31304ef
Create Date: 2025-06-18 10:11:08.386700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919f4bfab574'
down_revision: Union[str, None] = '8651b31304ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movies', ['title'])
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('code_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code_generated_at')
    op.drop_column('users', 'verification_code')
    op.drop_constraint(None, 'movies', type_='unique')
    # ### end Alembic commands ###
